update

diff --git a/ipabuilder b/ipabuilder
--- a/ipabuilder
+++ b/ipabuilder
@@ -6,75 +6,45 @@
 #xcodebuild -exportArchive -archivePath build/Tuanche.xcarchive/ -exportPath Test.ipa -exportOptionsPlist test.plist
 #
 #使用说明：
-#		当前工程目录下，不需要指定目录，编译project和workspace都使用：
-#			ipabuilder <schemeName> [-o <ipa output directory>] [-s <Code Signing Identity>] [-m <Provisioning Profile>]
-#		指定工程目录，编译project
-#			ipabuilder <schemeName> -p <project directory>	[-o <ipa output directory>] [-s <Code Signing Identity>] [-m <Provisioning Profile>]
-#		指定工程目录，编译workspace
-#			ipabuilder <schemeName> -w <workspace directory>	[-o <ipa output directory>] [-s <Code Signing Identity>] [-m <Provisioning Profile>]
+#	当前工程目录下，不需要指定目录，已经在工程中配置好证书和bundleId，不需要任何参数：
+#	ipabuilder
+#	指定工程目录，编译project
+#	ipabuilder -p <project directory> [-o <ipa output directory>] [-s <Code Signing Identity>] [-f <Provisioning Profile>] [-m <export method>] [-c <schemename>] [-b <bunlde identifier>]
+#	指定工程目录，编译workspace
+#	ipabuilder -w <workspace directory> [-o <ipa output directory>] [-s <Code Signing Identity>] [-f <Provisioning Profile>] [-m <export method>] [-c <schemename>] [-b <bunlde identifier>]
+
 #
 #可选参数：  
 #	-p PATH		project directory，默认当前目录
 #	-w PATH		workspace directory，默认当前目录
 #	-o PATH		输出ipa的文件目录，默认当前目录
 #	-s NAME		签名证书，不给值默认使用工程中的配置
-#	-m NAME		描述文件名的id，不给值默认使用工程中的配置
-#
+#	-f NAME		描述文件名的UDID，不给值默认使用工程中的配置
+#   -c NAME     指定scheme名称，默认使用工程项目名作为scheme
+#   -m NAME     指定method，现在只有app-store、enterprise、ad-hoc、development、空五种，默认为空
+#   -b NAME     指定工程的bundleId
+# 
 #---------------------------------------
-
-#查看必选参数是否传递
-if [ $# -lt 1 ];then
-	echo "Error: must input schemename"
-	exit 2
-fi
-
-#参数: $1 文件名  $2签名证书
-function createPlist() {
-	if [ $1 == "" ];then
-		echo "method: createPlist msg:please input file name"
-		return -1
-	fi
-	method="enterprise"
-	exportFormat="IPA"
-	exportSigningIdentity=""
-	exportInstallerIdentity=""
-	if [ "$2" != "" ];then
-		exportSigningIdentity="$2"
-		exportInstallerIdentity="$2"
-	fi
-	plistContent="<?xml version=\"1.0\" encoding=\"UTF-8\"?>
-				<!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\">
-				<plist version=\"1.0\">
-				<dict>
-					<key>method</key>
-					<string>$method</string>
-					<key>exportFormat</key>
-					<string>$exportFormat</string>
-					<key>exportSigningIdentity</key>
-					<string>$exportSigningIdentity</string>
-					<key>exportInstallerIdentity</key>
-					<string>$exportInstallerIdentity</string>
-				</dict>
-				</plist>"
-	echo $plistContent > $1
-}
 
 function usage() {
 	echo "
 使用说明：
-	当前工程目录下，不需要指定目录，编译project和workspace都使用：
-	ipabuilder <schemeName> [-o <ipa output directory>] [-s <Code Signing Identity>] [-m <Provisioning Profile>]
+	当前工程目录下，不需要指定目录，已经在工程中配置好证书和bundleId，不需要任何参数：
+	ipabuilder
 	指定工程目录，编译project
-	ipabuilder <schemeName> -p <project directory> [-o <ipa output directory>] [-s <Code Signing Identity>] [-m <Provisioning Profile>]
+	ipabuilder -p <project directory> [-o <ipa output directory>] [-s <Code Signing Identity>] [-f <Provisioning Profile>] [-m <export method>] [-c <schemename>] [-b <bunlde identifier>]
 	指定工程目录，编译workspace
-	ipabuilder <schemeName> -w <workspace directory> [-o <ipa output directory>] [-s <Code Signing Identity>] [-m <Provisioning Profile>]
+	ipabuilder -w <workspace directory> [-o <ipa output directory>] [-s <Code Signing Identity>] [-f <Provisioning Profile>] [-m <export method>] [-c <schemename>] [-b <bunlde identifier>]
 
 可选参数：  
 	-p PATH		project directory，默认当前目录
 	-w PATH		workspace directory，默认当前目录
 	-o PATH		输出ipa的文件目录，默认当前目录
 	-s NAME		签名证书，不给值默认使用工程中的配置
-	-m NAME		描述文件，不给值默认使用工程中的配置
+	-f NAME		描述文件名的UDID，不给值默认使用工程中的配置
+   	-c NAME     指定scheme名称，默认使用工程项目名作为scheme
+   	-m NAME     指定method，现在只有app-store、enterprise、ad-hoc、development、空五种，默认为空
+   	-b NAME     指定工程的bundleId
 "
 }
 
@@ -95,19 +65,17 @@ function findFileForGiveSuffix() {
 	fi
 }
 
-#scheme名
-build_scheme=$1
-
-#当前路径
+##########初始化默认值##########
 current_path=$(pwd)
 output_path=${current_path}
 project_path=${current_path}
+buildMethod=""
 #归档类型，默认为0，自己查找；1为project；2为workspace
 archiveType=0
 
 #后面带冒号，说明需要带参数
-param_pattern="p:w:o:s:m:h"
-OPTIND=2
+param_pattern="p:w:o:s:f:c:m:b:"
+OPTIND=1
 while getopts $param_pattern optname
 	do
 		#保存临时变量
@@ -161,9 +129,24 @@ while getopts $param_pattern optname
 		    "s")
 				build_sign=$tmp_optarg				
 		        ;;
-		    "m")
+		    "f")
 				build_profile=$tmp_optarg
 		        ;;
+		    "c")
+				buildSchemeName=$tmp_optarg
+				;;
+			"m")
+				#如果method不是app-store、enterprise、ad-hoc、development任何一种，则报错退出
+				if [ "$tmp_optarg" != "app-store" -a "$tmp_optarg" != "enterprise" -a "$tmp_optarg" != "ad-hoc" -a "$tmp_optarg" != "development" -a "$tmp_optarg" != "" ];then
+					echo "Error: Unknown option $tmp_optarg for -$optname"
+					usage
+					exit 2
+				fi
+				buildMethod=$tmp_optarg
+				;;
+			"b")
+				buildBundleId=$tmp_optarg
+				;;
 	        "?")
 		        echo "Error: Unknown option $OPTARG"
 		        usage
@@ -183,7 +166,12 @@ while getopts $param_pattern optname
 		esac
 	done
 
-#确定是workspace还是project
+#进入工程目录，并且去掉多余的/
+cd ${project_path}
+project_path=$(pwd)
+
+####这一段代码逻辑是查找workspace或者xcodeproj
+#归档类型，默认为0，自己查找；1为project；2为workspace
 if [ $archiveType == 2 ];then
 	findFileForGiveSuffix "xcworkspace"
 	commandPart=" -workspace $project_name"
@@ -203,15 +191,28 @@ else
 	fi
 fi
 
-#没有找到，则报错
 if [ $findReturnValue != 0 ];then
+	#没有找到，则报错
 	echo "Error: cant't find xcodeproj or xcworkspace file"
 	exit 2
+else
+	appName=$(echo "${project_name%.*}")
+	#如果没有设置-c参数，则自动以工程名为scheme名称
+	if [ "$buildSchemeName" = "" ];then
+		buildSchemeName="$appName"
+	fi
 fi
 
-#进入工程目录，并且去掉多余的/
-cd ${project_path}
-project_path=$(pwd)
+#设置了bundleId则，修改bundldId
+if [ "$buildBundleId" != "" ];then
+	echo "set Info.plist bunldId to $buildBundleId"
+	appInfoPlistPath=$project_path/$appName/Info.plist
+	/usr/libexec/PlistBuddy -c "Set :CFBundleIdentifier $buildBundleId" $appInfoPlistPath
+	appTestInfoPlistPath="$project_path/${appName}Tests/Info.plist"
+	/usr/libexec/PlistBuddy -c "Set :CFBundleIdentifier $buildBundleId" $appTestInfoPlistPath
+	appUITestInfoPlistPath="$project_path/${appName}UITests/Info.plist"
+	/usr/libexec/PlistBuddy -c "Set :CFBundleIdentifier $buildBundleId" $appUITestInfoPlistPath
+fi
 
 #create build path
 build_path="${project_path}/build"
@@ -220,18 +221,21 @@ if [ ! -d ${build_path} ];then
 fi
 
 #archive路径
-archive_path="${build_path}/${build_scheme}.xcarchive"
+archive_path="${build_path}/${buildSchemeName}.xcarchive"
 
 #make up build command
-build_cmd='xcodebuild archive'$commandPart
+build_cmd='xcodebuild archive '$commandPart
 
 cd $project_path
-build_cmd=${build_cmd}' -scheme '${build_scheme}' -archivePath '${archive_path}
+build_cmd=${build_cmd}' -scheme '${buildSchemeName}' -archivePath '${archive_path}
 if [ "$build_sign" != "" ];then
 	build_cmd="${build_cmd} CODE_SIGN_IDENTITY=\"$build_sign\""
 fi
 if [ "$build_profile" != "" ];then
 	build_cmd=${build_cmd}' PROVISIONING_PROFILE="'${build_profile}'"'
+fi
+if [ "$buildBundleId" != "" ];then
+	build_cmd=${build_cmd}' PRODUCT_BUNDLE_IDENTIFIER="'${buildBundleId}'"'
 fi
 
 echo $build_cmd
@@ -239,9 +243,30 @@ echo $build_cmd
 #开始打包，生成xcarchive文件
 eval ${build_cmd} || exit -1
 
-#生成exportOptionsPlist文件
+##################生成exportOptionsPlist文件###################
 exportOptionsPlist="exportOptionsPlist.plist"
-createPlist "$exportOptionsPlist" "$build_sign"
+buildFormat="IPA"
+#删除文件
+if [ -f $exportOptionsPlist ];then
+	rm $exportOptionsPlist
+fi
+#生成plist文件
+/usr/libexec/PlistBuddy -c save $exportOptionsPlist
+#设置method
+if [ "$buildMethod" != "" ];then
+	/usr/libexec/PlistBuddy -c "Add :method string \"$buildMethod\"" $exportOptionsPlist
+fi
+
+#设置导出格式
+if [ "$buildFormat" != "" ];then
+	/usr/libexec/PlistBuddy -c "Add :exportFormat string \"$buildFormat\"" $exportOptionsPlist
+fi
+
+#如果设置了签名证书，则添加
+if [ "$build_sign" != "" ];then
+	/usr/libexec/PlistBuddy -c "Add :exportSigningIdentity string \"$build_sign\"" $exportOptionsPlist
+	/usr/libexec/PlistBuddy -c "Add :exportInstallerIdentity string \"$build_sign\"" $exportOptionsPlist
+fi
 
 #导出ipa包
 xcodebuild -exportArchive -archivePath ${archive_path} -exportPath $output_path -exportOptionsPlist $exportOptionsPlist
